version: '3'

services:
  postgres:
    image: postgres:alpine3.18
    container_name: postgres-slovar  
    ports:
      - 5435:5432  # Пробрасываем порт 5432 контейнера на порт 5432 хоста
    volumes:
      - ${HOME}/pgdata/:/var/lib/postgresql/data  
    environment:
      POSTGRES_PASSWORD: 1 

       